contact/urls.py
""" urls for the contact app. """
from django.urls import path
from . import views

urlpatterns = [
    path('', views.contact, name='contact'),
    path('manage/', views.manage_contacts, name='manage_contacts'),
    path(
        'toggle/<int:contact_message_id>/',
        views.toggle_responded, name='toggle_responded'),
]

faqs/urls.py
""" urls for the faqs app. """
from django.urls import path
from . import views

urlpatterns = [
    path('', views.faqs, name='faqs'),
    path('add/', views.add_faq, name='add_faq'),
    path('edit/<int:faq_id>/', views.edit_faq, name='edit_faq'),
    path('delete/<int:faq_id>/', views.delete_faq, name='delete_faq'),
]

jewellery_art/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('allauth.urls')),
    path('products/', include('products.urls')),
    path('designers/', include('designers.urls')),
    path('basket/', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
    path('faqs/', include('faqs.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
""" Models for the contact app. """
from django.db import models


class ContactMessage(models.Model):
    """
    Contact Message model for messages left by customers.
    """
    # Set topic options
    ORDER = 'OR'
    PRODUCT = 'PR'
    DESIGNER = 'DS'
    WEBSITE = 'WB'
    OTHER = 'OT'
    TOPIC_CHOICES = [
        ('', 'Select Topic *'),
        (ORDER, 'Jewellery Order'),
        (PRODUCT, 'Jewellery Product'),
        (DESIGNER, 'Jewellery Designer'),
        (WEBSITE, 'Our Website'),
        (OTHER, 'Other'),
    ]

    topic = models.CharField(max_length=2, choices=TOPIC_CHOICES)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    message = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    responded = models.BooleanField(default=False)

    class Meta:
        """
        Set ordering to ensure newest messages are displayed first.
        """
        ordering = ['-date_created']

    def __str__(self):
        return f'Message from {self.first_name} {self.last_name}'

contact/forms.py
""" Forms for the contact app. """
from django import forms

from .models import ContactMessage


class ContactForm(forms.ModelForm):
    """
    A form to add a customer contact message.
    """
    class Meta:
        """ Select the model and define the fields. """
        model = ContactMessage
        fields = ('topic', 'first_name', 'last_name',
                  'email', 'phone_number', 'message')

    def __init__(self, *args, **kwargs):
        """ Add placeholders to fields. """
        super().__init__(*args, **kwargs)
        placeholders = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'email': 'Email Address',
            'phone_number': 'Phone Number',
            'message': 'Add your comment or query here.'
        }

        for field in self.fields:
            if field != 'topic':
                if self.fields[field].required:
                    placeholder = f'{placeholders[field]} *'
                else:
                    placeholder = placeholders[field]
                self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[field].label = False

contact/views.py
""" Views for the contact app. """
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .forms import ContactForm
from .models import ContactMessage
from .summary_email import send_summary_email


def contact(request):
    """
    A view to return the contact page.
    """
    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_message = contact_form.save()
            send_summary_email(contact_message)
            messages.success(
                request, f'Thank you for your message. \
                    A summary has been sent to {contact_message.email}. \
                    We will get back to you as soon as we can.')
            return redirect(reverse('home'))
        else:
            messages.error(
                request, 'It has not been possible to submit your message. \
                    Please check the form.')
    else:
        contact_form = ContactForm()

    context = {
        'contact_form': contact_form,
    }

    return render(request, 'contact/contact.html', context)


@login_required
def manage_contacts(request):
    """
    List customer contact messages for the store owner.
    """
    if not request.user.is_superuser:
        messages.error(
            request, 'Sorry this area is for the store owner only.')
        return redirect(reverse('home'))

    contact_messages = ContactMessage.objects.all()

    context = {
        'contact_messages': contact_messages
    }

    return render(request, 'contact/manage_contacts.html', context)


@login_required
def toggle_responded(request, contact_message_id):
    """
    Toggle the responded field of an individual contact message.
    """
    if not request.user.is_superuser:
        messages.error(
            request, 'Sorry, only store owners are authorised to do that.')
        return redirect(reverse('home'))

    contact_message = get_object_or_404(ContactMessage, pk=contact_message_id)
    contact_message.responded = not contact_message.responded
    contact_message.save()

    return redirect(reverse('manage_contacts'))

contact/templates/contact/contact.html
{% extends "base.html" %}

{% block extra_title %}Contact Us{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 mt-4 mb-2 txt-drk">
            <h1 class="mb-0">Contact Us</h1>
        </div>
        <div class="col-12">
            <hr class="divide-rule">
        </div>
        <div class="col-12 col-md-10 col-lg-8 mx-auto mb-4 txt-drk">
            <p>
                If you have any comments or queries, fill out the form below and we will get back to you as soon as we
                can.
            </p>
            <form class="order-fieldset" method="POST" action="{% url 'contact' %}">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12">
                        {{ contact_form.topic | as_crispy_field }}
                    </div>
                    <div class="col-12 col-sm-6">
                        {{ contact_form.first_name | as_crispy_field }}
                    </div>
                    <div class="col-12 col-sm-6">
                        {{ contact_form.last_name | as_crispy_field }}
                    </div>
                    <div class="col-12 col-sm-6">
                        {{ contact_form.email | as_crispy_field}}
                    </div>
                    <div class="col-12 col-sm-6">
                        {{ contact_form.phone_number | as_crispy_field}}
                    </div>
                    <div class="col-12">
                        {{ contact_form.message | as_crispy_field }}
                    </div>
                </div>
                <button class="btn btn-sm btn-drk btn-sqr txt-lgt" type="submit">Send Message</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

contact/templates/contact/manage_contacts.html
{% extends "base.html" %}

{% block extra_title %}Manage Contact Messages{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 mt-4 mb-2 txt-drk">
            <h1 class="mb-0">Customer Message Management</h1>
        </div>
        <div class="col-12">
            <hr class="divide-rule">
        </div>
    </div>
    <div class="row">
        <div class="col-12 mb-4 txt-drk">
            {% if contact_messages %}
                {% for message in contact_messages %}
                    {% if not message.responded %}
                        <!-- Flag to indicate the message hasn't been responded to -->
                        <p class="mb-1"><i class="fas fa-exclamation-circle mr-2 txt-red"></i>Awaiting Response</p>
                    {% endif %}
                    <p class="mb-0"><span class="font-weight-bold">From:</span> {{ message.first_name }} {{ message.last_name }}
                    </p>
                    <p class="mb-0"><span class="font-weight-bold">Email:</span> {{ message.email }}</p>
                    {% if message.phone_number %}
                        <p class="mb-0"><span class="font-weight-bold">Phone Number:</span> {{ message.phone_number}}</p>
                    {% endif %}
                    <p class="font-weight-bold">On {{ message.date_created|date:"jS F Y"}} at
                        {{ message.date_created|date:"H:i"}}</p>
                    <p><span class="font-weight-bold">Message Topic:</span> {{ message.get_topic_display }}</p>
                    <p class="font-weight-bold mb-0">Message Body:</p>
                    <p>{{ message.message }}</p>
                    {% if message.responded %}
                        <!-- Button to turn on or off the awaiting response flag -->
                        <a role="button" class="btn btn-sm btn-drk btn-sqr txt-lgt mb-4"
                            href="{% url 'toggle_responded' message.id %}" aria-label="Set as requiring a response">Mark as Response
                            Required</a>
                    {% else %}
                        <a role="button" class="btn btn-sm btn-drk btn-sqr txt-lgt mb-4"
                            href="{% url 'toggle_responded' message.id %}" aria-label="Confirm a response has been sent">Mark as
                            Responded</a>
                    {% endif %}
                    {% if not forloop.last %}
                        <!-- Divider separating the messages, not displayed below the last -->
                        <hr class="divide-rule-grey">
                    {% endif %}
                {% endfor %}
            {% else %}
                <p class="txt-lrg">There are currently no customer messages to see.</p>
                <a class="btn btn-drk btn-sqr txt-lgt mt-1 mb-4" aria-label="Go to the Jewellery Art home page"
                    href="{% url 'home' %}">Go to the Homepage</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}